name: Generate and Publish RSS Feed

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate RSS XML
        run: |
          OUTPUT_FILE=publish/rss.xml python rss.py

      - name: Deploy to gh-pages
        run: |
          mv static/*.* publish/
          mv media/*.* publish/
          mv index.html publish/

      - name: Push to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
          publish_branch: gh-pages
